application: bingo-test
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:
- url: /gae_bingo/static
  static_dir: gae_bingo/static
- url: /gae_bingo/tests/.*
  script: gae_bingo/tests/main.py
- url: /gae_bingo/.*
  script: gae_bingo/main.py
- url: /.*
  script: main.py
